sudo: false
language: ruby
rvm: 2.4.0
cache:
  bundler: true
  directories:
    - ~/.rvm/gems/ruby-2.4.0
    - ~/.nvm
    - node_modules
services:
  - postgresql
  - redis-server
env:
  - TEST_TYPE=rspec
  - TEST_TYPE=rubocop
  - TEST_TYPE=eslint
before_install:
  - "gem update --system"
  - "echo 'gem: --no-document' > ~/.gemrc"
  - "curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.0/install.sh | bash"
  - "export NVM_DIR=\"$HOME/.nvm\""
  - ". \"$NVM_DIR/nvm.sh\""
  - "nvm install 6.5.0"
  - "nvm use 6.5.0"
install:
  - travis_retry bin/setup
script: bin/test
